### GET all persons
#GET http://localhost:3001/api/persons

### GET info
GET http://localhost:3003/api/blogs

### GET specific person
#GET http://localhost:3001/api/persons/3

### DELETE entry
#DELETE http://localhost:3001/api/persons/3

### POST new entry
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1haWsiLCJpZCI6IjZhNzQxMDYyZTJkOGRhNTNhNTAxYzI3YSIsImlhdCI6MTc4NTk5NjM1Nn0.yt5TLCQIIB9doJdR3Apd28Dv8n1o35NTXQziIAeRJTE

{
  "title": "ab",
  "author": "12-43-234345123123123123",
  "url": "asdefgasdf",
  "likes": "4"
}
### DELETE entry
DELETE http://localhost:3003/api/blogs/6a74310dc6d2d22c3c568a72
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1haWsiLCJpZCI6IjZhNzQxMDYyZTJkOGRhNTNhNTAxYzI3YSIsImlhdCI6MTc4NTk5ODA2NH0.ogRQx8uCBpwjjlKQh6C7UTdLJ1xomFjhCCfnKYyPkpI

### Update blog
PUT http://localhost:3003/api/blogs/5a422bc61b54a676234d17fc
Content-Type: application/json

{
  "likes": "7"
}


#### User
### User post
POST http://localhost:3003/api/users/
Content-Type: application/json

{
  "username": "Maik",
  "name": "Maik",
  "password": "Maik"
}

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "Maik",
  "password": "Maik"
}