### GET request to example server
GET http://localhost:3001/api/notes

###

### DELETE request to example server
DELETE http://localhost:3001/api/notes/3


###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2YTY4NGM2YjkzMWI1ZGNkZjA2N2IwZTMiLCJpYXQiOjE3ODUyMjYzMzV9.xiVGnQpvZ7s7jWxIv1ZxXWTItfSB5_uQILwgS7wvVI8

{
  "content": "abcdesdfghsdfhsdfh",
  "important": true
}

###
DELETE  http://localhost:3001/api/notes/6a477525b1e1c73b16f1a578

#### User
### User post
POST http://localhost:3001/api/users/
Content-Type: application/json

{
  "username": "Maik",
  "name": "Superuser",
  "password": "123"
}

###
GET http://localhost:3001/api/users/
###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "UserMaik",
  "password": "12345"
}

