### GET request to example server
GET http://localhost:3001/api/notes/3

###

### DELETE request to example server
DELETE http://localhost:3001/api/notes/3


###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "WebStorm is best",
  "important": true
}